# Generated by Django 5.2.17 on 2026-08-28 20:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('external_id', models.CharField(blank=True, default='', max_length=120, verbose_name='id externo')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('price_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio al contado')),
                ('price_financed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='precio financiado anunciado')),
                ('mileage_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='kilómetros')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='fecha de matriculación')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='provincia')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='localidad')),
                ('warranty_months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='garantía (meses)')),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('reservado', 'Reservado'), ('vendido', 'Vendido'), ('retirado', 'Retirado'), ('desconocido', 'Desconocido')], default='activo', max_length=20, verbose_name='estado')),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='primera vez visto')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='última vez visto')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado el')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='datos originales')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='sources.seller', verbose_name='vendedor')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='sources.source', verbose_name='fuente')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='vehicles.vehicle', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'anuncio',
                'verbose_name_plural': 'anuncios',
                'db_table': 'listings_listing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='capturado el')),
                ('price_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio al contado')),
                ('price_financed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio financiado')),
                ('mileage_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='kilómetros')),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('reservado', 'Reservado'), ('vendido', 'Vendido'), ('retirado', 'Retirado'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20, verbose_name='estado')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='datos originales')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='listings.listing', verbose_name='anuncio')),
            ],
            options={
                'verbose_name': 'captura de anuncio',
                'verbose_name_plural': 'capturas de anuncio',
                'db_table': 'listings_listing_snapshot',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='uniq_listing_source_external_id'),
        ),
    ]
