# Generated by Django 5.2.17 on 2026-09-01 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='archivado el'),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Usuario que dio de alta el anuncio a mano; nulo para anuncios de otras fuentes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_listings', to=settings.AUTH_USER_MODEL, verbose_name='propietario'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URL'),
        ),
    ]
