# Generated by Django 5.2.17 on 2026-09-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_archived_at_listing_owner_alter_listing_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='tracking_status',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('interesado', 'Interesado'), ('contactado', 'Contactado'), ('visita', 'Visita'), ('descartado', 'Descartado'), ('comprado', 'Comprado')], default='nuevo', max_length=20, verbose_name='estado de seguimiento'),
        ),
    ]
