# Generated by Django 5.2.17 on 2026-08-28 20:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('website', models.URLField(blank=True, max_length=300, verbose_name='web')),
                ('integration_type', models.CharField(choices=[('manual', 'Entrada manual'), ('user_import', 'Importación por URL'), ('api', 'API'), ('feed', 'Feed'), ('affiliate', 'Programa de afiliación'), ('scraper', 'Scraper autorizado')], default='manual', max_length=20, verbose_name='tipo de integración')),
                ('enabled', models.BooleanField(default=True, verbose_name='activa')),
                ('commercial_use_allowed', models.BooleanField(default=False, verbose_name='uso comercial permitido')),
                ('images_allowed', models.BooleanField(default=False, verbose_name='imágenes permitidas')),
                ('refresh_policy', models.CharField(blank=True, max_length=200, verbose_name='política de refresco')),
                ('terms_reviewed_at', models.DateField(blank=True, null=True, verbose_name='términos revisados el')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'fuente',
                'verbose_name_plural': 'fuentes',
                'db_table': 'sources_source',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('external_id', models.CharField(blank=True, default='', max_length=120, verbose_name='id externo')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='nombre')),
                ('type', models.CharField(choices=[('particular', 'Particular'), ('profesional', 'Profesional'), ('marketplace', 'Marketplace'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20, verbose_name='tipo')),
                ('website', models.URLField(blank=True, max_length=300, verbose_name='web')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='teléfono')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='ubicación')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='valoración')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sellers', to='sources.source', verbose_name='fuente')),
            ],
            options={
                'verbose_name': 'vendedor',
                'verbose_name_plural': 'vendedores',
                'db_table': 'sources_seller',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='uniq_seller_source_external_id')],
            },
        ),
    ]
