# Generated by Django 5.2.17 on 2026-08-28 21:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='puntuación')),
                ('version', models.CharField(max_length=20, verbose_name='versión de la fórmula')),
                ('breakdown', models.JSONField(default=dict, verbose_name='desglose explicativo')),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='calculado el')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='listings.listing', verbose_name='anuncio')),
                ('user', models.ForeignKey(blank=True, help_text='Vacío = puntuación genérica sin preferencias de usuario.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'puntuación',
                'verbose_name_plural': 'puntuaciones',
                'db_table': 'scoring_score',
                'ordering': ['-calculated_at'],
                'constraints': [models.UniqueConstraint(fields=('listing', 'user', 'version'), name='uniq_score_listing_user_version', nulls_distinct=False)],
            },
        ),
    ]
