# Generated by Django 5.2.17 on 2026-08-28 20:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='entrada')),
                ('amount_financed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='importe financiado')),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cuota mensual')),
                ('number_of_payments', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='número de cuotas')),
                ('final_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cuota final')),
                ('opening_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='comisión de apertura')),
                ('tin', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='TIN (%)')),
                ('tae', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='TAE (%)')),
                ('mandatory_products_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='coste de productos obligatorios')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='coste total anunciado')),
                ('source_text', models.TextField(blank=True, verbose_name='texto original de la oferta')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_offers', to='listings.listing', verbose_name='anuncio')),
            ],
            options={
                'verbose_name': 'oferta de financiación',
                'verbose_name_plural': 'ofertas de financiación',
                'db_table': 'finance_finance_offer',
                'ordering': ['-created_at'],
            },
        ),
    ]
