# Generated by Django 5.2.17 on 2026-08-28 20:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('budget_target', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='presupuesto objetivo')),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='presupuesto máximo')),
                ('max_mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='kilometraje máximo')),
                ('min_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='año mínimo')),
                ('fuel_types', models.JSONField(blank=True, default=list, verbose_name='combustibles aceptados')),
                ('body_types', models.JSONField(blank=True, default=list, verbose_name='carrocerías aceptadas')),
                ('weight_price', models.PositiveSmallIntegerField(default=25, verbose_name='peso · precio')),
                ('weight_mileage', models.PositiveSmallIntegerField(default=20, verbose_name='peso · kilómetros')),
                ('weight_age', models.PositiveSmallIntegerField(default=15, verbose_name='peso · antigüedad')),
                ('weight_reliability', models.PositiveSmallIntegerField(default=15, verbose_name='peso · fiabilidad')),
                ('weight_consumption', models.PositiveSmallIntegerField(default=10, verbose_name='peso · consumo')),
                ('weight_financing', models.PositiveSmallIntegerField(default=10, verbose_name='peso · financiación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'preferencia de usuario',
                'verbose_name_plural': 'preferencias de usuario',
                'db_table': 'accounts_user_preference',
            },
        ),
    ]
