# Generated by Django 5.2.17 on 2026-08-28 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('make', models.CharField(max_length=80, verbose_name='marca')),
                ('model', models.CharField(max_length=120, verbose_name='modelo')),
                ('generation', models.CharField(blank=True, max_length=120, verbose_name='generación')),
                ('version', models.CharField(blank=True, max_length=200, verbose_name='versión')),
                ('body_type', models.CharField(blank=True, max_length=60, verbose_name='carrocería')),
                ('fuel_type', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('hibrido', 'Híbrido'), ('hibrido_enchufable', 'Híbrido enchufable'), ('electrico', 'Eléctrico'), ('glp', 'GLP (autogás)'), ('gnc', 'GNC (gas natural)'), ('otro', 'Otro'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20, verbose_name='combustible')),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática'), ('desconocida', 'Desconocida')], default='desconocida', max_length=20, verbose_name='cambio')),
                ('engine_displacement', models.PositiveIntegerField(blank=True, null=True, verbose_name='cilindrada (cc)')),
                ('power_kw', models.PositiveIntegerField(blank=True, null=True, verbose_name='potencia (kW)')),
                ('power_cv', models.PositiveIntegerField(blank=True, null=True, verbose_name='potencia (CV)')),
                ('doors', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='puertas')),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='plazas')),
                ('first_registration_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='año de matriculación')),
                ('emissions_label', models.CharField(blank=True, max_length=10, verbose_name='etiqueta ambiental')),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
                'db_table': 'vehicles_vehicle',
                'ordering': ['make', 'model'],
            },
        ),
    ]
